-- Atlas Check-In core tables bootstrap
-- Run this BEFORE other seed scripts (supabase_schema_only.sql, seeds, migrations).
-- Intended for fresh Supabase projects created for feature branches / preview envs.

-- 1) Core lookup table for locations (id seeded with Atlas Gym as default site)
create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  timezone text default 'UTC'
);

-- 2) Members directory (mirrors production schema expectations)
create table if not exists public.members (
  id bigint generated by default as identity primary key,
  external_id text,
  name text not null,
  email_lower text,
  phone_e164 text,
  membership_tier text,
  status text not null default 'active' check (status in ('active','inactive')),
  qr_token text,
  stripe_customer_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_members_external on public.members(external_id);
create index if not exists idx_members_email on public.members(email_lower);
create index if not exists idx_members_phone on public.members(phone_e164);

-- 3) Check-in ledger (references members + locations)
create table if not exists public.check_ins (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  location_id bigint not null references public.locations(id),
  timestamp timestamptz not null default now(),
  method text not null check (method in ('QR','manual')),
  source_device_id text,
  status text not null default 'ok'
);

create index if not exists idx_checkins_member_time on public.check_ins(member_id, timestamp);

-- 4) Staff PIN table for kiosk/admin auth
create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  name text,
  pin_salt text not null,
  pin_hash text not null,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

-- 5) Seed default location so FK references resolve cleanly
insert into public.locations (id, name, timezone)
values (1, 'Atlas Gym', 'America/Los_Angeles')
on conflict (id) do nothing;
