-- Guests table to capture walk-in sales
CREATE TABLE IF NOT EXISTS public.guests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email_lower TEXT UNIQUE,
  phone_e164 TEXT,
  stripe_customer_id TEXT,
  last_order_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_guests_email_lower ON public.guests(email_lower);
CREATE INDEX IF NOT EXISTS idx_guests_stripe_customer ON public.guests(stripe_customer_id);

DROP TRIGGER IF EXISTS trg_guests_updated_at ON public.guests;
CREATE TRIGGER trg_guests_updated_at
  BEFORE UPDATE ON public.guests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Ensure order columns exist for guest/member linkage
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS guest_name TEXT;
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS guest_email TEXT;
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS member_id BIGINT REFERENCES public.members(id);
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS guest_id BIGINT REFERENCES public.guests(id);
